### ISSUE TITLE
Tailwind Custom Base Styles

### ISSUE THREAD

**Issue by werdna521** [bearcatsdev/adab-web#11]
According to [Tailwind's official documentation](https://tailwindcss.com/docs/adding-base-styles#using-css), custom base styles are supposed to be defined directly after `@tailwind base` and before `@tailwind components` to avoid specificity issues. The code in main.css should also follow this rule

**Comment by AngSanley** [comment]
Oops, I didn't know that. Can you make a pull request to fix that?

**Comment by werdna521** [comment]
I've made my pull request to fix this issue. Please review it #12
