### ISSUE TITLE
User profile doesn't get loaded when opening session page directly

### ISSUE THREAD

**Issue by AngSanley** [bearcatsdev/adab-web#15]
User profile data does not get loaded when we opening session page directly from browser without going though dashboard first, e.g opening https://adab.bearcats.dev/app/session/1 directly from browser address bar.

![Screen Shot 2020-07-13 at 08 25 07](https://user-images.githubusercontent.com/4332289/87261940-5d963700-c4e2-11ea-8684-42d2ee83104b.png)

Notice that the user's name and email are empty. This could lead to other problems such as the "Start talking" button not showing for users that have `can_talk` privilege.

This is because the user's profile data is loaded by dashboard, and by loading session page directly, this data doesn't get loaded.

Currently the workaround for this is to go back to dashboard, and opening the session from the dashboard page.

**Comment by brianrahula** [comment]
Is anyone currently working on this issue?

**Comment by AngSanley** [comment]
Maybe @werdna521 can help?

**Comment by werdna521** [comment]
I'll see what I can do about it
