### ISSUE TITLE
Bottom Tab Blocking Views on Small Screens

### ISSUE THREAD

**Issue by werdna521** [bearcatsdev/adab-web#25]
The bottom part of the screen is blocked by the bottom tab on smaller screens.

## Expected Behavior
No content should ever be blocked by the tab bar. Every content should be accessible and readable by users using any kind of device, in this case, a mobile phone (or any other device with small screens).

## Current Behavior
Every time the content is larger than the phone screen, the bottom part of the content is blocked by the bottom tab (the content goes under the bottom tab) as shown in the following picture.

![image](https://user-images.githubusercontent.com/48923485/88210782-e9e0f080-cc7e-11ea-8862-5962d05d43f4.png)

## Possible Solution
Adding margin on the bottom of the content (approximately a little larger than the bottom tab's height) might work.

## Steps to Reproduce
1. Login at [https://adab.bearcats.dev/login](https://adab.bearcats.dev/login) using a mobile phone or a shrunk desktop browser.
2. Enter a class that has long session notes (larger than screen height).
3. Try to scroll to the bottom of the page.
4. The problem happens similar to the screenshot above.

## Context (Environment)
```
System:
    OS: Windows 10 Home Single Language 1903
    Processor: Intel(R) Core(TM) i7-4500U CPU @ 1.80GHz
    RAM: 8.00 GB

Browser: Mozilla Firefox 78.02
```

**Comment by brianrahula** [comment]
The new design is already being worked on my Repo, I will update on this later
