### ISSUE TITLE
Page Not Found

### ISSUE THREAD

**Issue by brianrahula** [bearcatsdev/adab-web#5]
The page I tried to open isn't working. Are there any problems here?

![image](https://user-images.githubusercontent.com/45139213/87064002-56003500-c239-11ea-8b15-6e1d72313b3a.png)

**Comment by AngSanley** [comment]
Oops. My bad! I'll fix it now, thanks for informing me!

**Comment by AngSanley** [comment]
It should be fixed now 😀
